import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import TransitionProvider from "@/components/TransitionProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ana Dev Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" /> {/* Add viewport meta tag */}
        <TransitionProvider>{children}</TransitionProvider>
      </body>
    </html>
  );
}
